language: node_js

node_js:
  - 4.0
  - 4
  - 5

env:
    - HAPI_VERSION="11"
    - HAPI_VERSION="12"
    - HAPI_VERSION="13"

install:
    - npm install
    - npm install hapi@$HAPI_VERSION

sudo: false